version: '3.8'

services:
  products-service:
    container_name: products_service
    build:
      context: ./services/products-service
      dockerfile: Dockerfile
    volumes:
      - ./services/products-service:/usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - products-db
    env_file:
      - ./services/products-service/.env
    networks:
      - micro-net

  products-db:
    image: postgres:16
    container_name: products_db
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5433:5432"
    networks:
      - micro-net

  stocks-service:
    container_name: stocks_service
    build:
      context: ./services/stocks-service
      dockerfile: Dockerfile
    volumes:
      - ./services/stocks-service:/usr/src/app
    ports:
      - "3002:3000"
    depends_on:
      - stocks-db
    env_file:
      - ./services/stocks-service/.env
    networks:
      - micro-net

  stocks-db:
    image: postgres:16
    container_name: stocks_db
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
    ports:
      - "5434:5432"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
